site_name: Rodrunner
site_description: Documentation for iRODS Prefect v3 workflows for sequencer data management
site_author: Bilgehan Nevruz
repo_url: https://github.com/bilgehannevruz/rodrunner
repo_name: rodrunner

theme:
  name: mkdocs
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quickstart: getting-started/quickstart.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Filesystem Operations: user-guide/filesystem.md
    - iRODS Client: user-guide/irods-client.md
    - Parsers: user-guide/parsers.md
    - Workflows: user-guide/workflows.md
    - API: user-guide/api.md
  - Sequencer Types:
    - MiSeq: sequencers/miseq.md
    - NovaSeq: sequencers/novaseq.md
    - Other Sequencers: sequencers/other.md
  - API Reference:
    - Filesystem: api-reference/filesystem.md
    - iRODS Client: api-reference/irods-client.md
    - Parsers: api-reference/parsers.md
    - Workflows: api-reference/workflows.md
    - API Endpoints: api-reference/api-endpoints.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Docker: development/docker.md
  - About:
    - License: about/license.md
    - Changelog: about/changelog.md
